### ISSUE TITLE
Support namespace packages

### ISSUE THREAD

**Issue by Stealthii** [tiangolo/poetry-version-plugin#43]
Currently poetry-version-plugin trips over namespace packages as no `__init__.py` is present in the parent namespace.

Example package: mycompany-mypackage
Path: `mycompany/mypackage/__init__.py`
Poetry config:
```toml
[tool.poetry]
packages = [
   {include = "mycompany", from = "."},
]
[tool.poetry-version-plugin]
source = "init"
```
Output:
```
poetry-version-plugin: __init__.py file not found at mycompany/__init__.py cannot extract dynamic version
poetry-version-plugin: __init__.py file not found at mycompany/__init__.py cannot extract dynamic version
```
